export interface WorkoutExerciseSeed {
  name: string;
  block: string;
  targetSets: number;
  targetRepsMin: number;
  targetRepsMax: number;
  bodyPart: "upper" | "lower";
  exerciseType?: "reps" | "time" | "warmup";
  progressionMode?: "weight" | "assist";
  progressionStep?: number;
  restTimeInSeconds: number;
  baselineWeightMin?: number;
  baselineWeightMax?: number;
  baselineNote?: string;
  technique?: string;
}

export interface WorkoutDaySeed {
  dayNumber: number;
  weekday: string;
  name: string;
  exercises: WorkoutExerciseSeed[];
}

/** Важкі базові вправи */
export const REST_HEAVY = 120;
/** Важкі ізольовані тренажери та тяги */
export const REST_MACHINE = 90;
/** Мала ізоляція, плечі та руки */
export const REST_ISOLATION = 60;

export const PROGRAM_VERSION = 7;

export const WARMUP_EXERCISE: WorkoutExerciseSeed = {
  name: "Прес — підняття ніг на брусях",
  block: "Розминка",
  targetSets: 4,
  targetRepsMin: 15,
  targetRepsMax: 15,
  bodyPart: "upper",
  exerciseType: "warmup",
  progressionStep: 0,
  restTimeInSeconds: REST_ISOLATION,
  technique: "Підняття ніг вгору на брусях, контрольований темп",
};

function withWarmup(exercises: WorkoutExerciseSeed[]): WorkoutExerciseSeed[] {
  return [WARMUP_EXERCISE, ...exercises];
}

export { classifyMuscleGroup } from "../src/services/muscle";

export const workoutProgram: WorkoutDaySeed[] = [
  {
    dayNumber: 1,
    weekday: "Понеділок",
    name: "Верх A (горизонтальні жими та тяги)",
    exercises: withWarmup([
      {
        name: "Жим гантелей лежачи (горизонтальна лава)",
        block: "Гантелі",
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        bodyPart: "upper",
        progressionStep: 2,
        restTimeInSeconds: REST_HEAVY,
        baselineWeightMin: 14,
        baselineWeightMax: 14,
        baselineNote: "2×14 кг",
      },
      {
        name: "Тяга гантелі до пояса в нахилі (однією рукою з упором)",
        block: "Гантелі",
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        bodyPart: "upper",
        progressionStep: 2,
        restTimeInSeconds: REST_MACHINE,
        baselineWeightMin: 14,
        baselineWeightMax: 14,
        baselineNote: "14 кг",
      },
      {
        name: "Жим гантелей сидячи (вертикальний жим)",
        block: "Гантелі",
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 12,
        bodyPart: "upper",
        progressionStep: 2,
        restTimeInSeconds: REST_MACHINE,
        baselineWeightMin: 10,
        baselineWeightMax: 10,
        baselineNote: "2×10 кг",
      },
      {
        name: "Тяга верхнього блоку до грудей паралельним хватом",
        block: "Тренажери",
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 12,
        bodyPart: "upper",
        progressionStep: 2,
        restTimeInSeconds: REST_MACHINE,
        baselineWeightMin: 39,
        baselineWeightMax: 39,
        baselineNote: "39 кг",
      },
      {
        name: "Махи гантелей в сторони (Lateral Raises)",
        block: "Гантелі",
        targetSets: 4,
        targetRepsMin: 12,
        targetRepsMax: 15,
        bodyPart: "upper",
        progressionStep: 2,
        restTimeInSeconds: REST_ISOLATION,
        baselineWeightMin: 6,
        baselineWeightMax: 6,
        baselineNote: "2×6 кг",
      },
      {
        name: "Почерговий підйом на біцепс стоячи (з супінацією)",
        block: "Гантелі",
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 12,
        bodyPart: "upper",
        progressionStep: 2,
        restTimeInSeconds: REST_ISOLATION,
        baselineWeightMin: 12,
        baselineWeightMax: 12,
        baselineNote: "2×12 кг",
      },
      {
        name: "Французький жим з гантеллю з-за голови",
        block: "Гантелі",
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 12,
        bodyPart: "upper",
        progressionStep: 2,
        restTimeInSeconds: REST_ISOLATION,
        baselineWeightMin: 12,
        baselineWeightMax: 12,
        baselineNote: "12 кг",
        technique: "Двома руками, контрольоване опускання за голову",
      },
    ]),
  },
  {
    dayNumber: 2,
    weekday: "Середа",
    name: "Низ A (акцент квадрицепс)",
    exercises: withWarmup([
      {
        name: "Goblet Squats (присідання з гантеллю перед грудьми)",
        block: "Гантелі",
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        bodyPart: "lower",
        progressionStep: 2,
        restTimeInSeconds: REST_HEAVY,
        baselineWeightMin: 20,
        baselineWeightMax: 20,
        baselineNote: "20 кг",
      },
      {
        name: "Жим ногами в тренажері (Leg Press)",
        block: "Тренажери",
        targetSets: 4,
        targetRepsMin: 10,
        targetRepsMax: 12,
        bodyPart: "lower",
        progressionStep: 5,
        restTimeInSeconds: REST_HEAVY,
        baselineWeightMin: 80,
        baselineWeightMax: 80,
        baselineNote: "80 кг",
        technique: "Стопи на ширині плечей, не розгинай коліна до кінця",
      },
      {
        name: "Згинання ніг лежачи / сидячи (Leg Curls)",
        block: "Тренажери",
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 15,
        bodyPart: "lower",
        progressionStep: 2,
        restTimeInSeconds: REST_MACHINE,
        baselineWeightMin: 32,
        baselineWeightMax: 32,
        baselineNote: "32 кг",
      },
      {
        name: "Підйоми на носки стоячи (Standing Calf Raises)",
        block: "Тренажери",
        targetSets: 4,
        targetRepsMin: 12,
        targetRepsMax: 20,
        bodyPart: "lower",
        progressionStep: 5,
        restTimeInSeconds: REST_ISOLATION,
        baselineWeightMin: 50,
        baselineWeightMax: 50,
        baselineNote: "50 кг",
        technique: "Повна амплітуда: глибоко вниз, максимально вгору, пауза зверху",
      },
      {
        name: "Скручування на блоці (Cable Crunch)",
        block: "Прес",
        targetSets: 3,
        targetRepsMin: 15,
        targetRepsMax: 20,
        bodyPart: "upper",
        progressionStep: 2,
        restTimeInSeconds: REST_ISOLATION,
        baselineWeightMin: 25,
        baselineWeightMax: 25,
        baselineNote: "25 кг",
        technique: "Скругли спину, тягни ребрами до таза, без ривків",
      },
    ]),
  },
  {
    dayNumber: 3,
    weekday: "П'ятниця",
    name: "Верх B (вертикальні жими та тяги)",
    exercises: withWarmup([
      {
        name: "Віджимання на брусях у Гравітоні",
        block: "Гравітрон (Бруси)",
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 10,
        bodyPart: "upper",
        progressionMode: "assist",
        progressionStep: 2,
        restTimeInSeconds: REST_HEAVY,
        baselineWeightMin: 23,
        baselineWeightMax: 23,
        baselineNote: "противага 23 кг",
        technique:
          "Широкі ручки, корпус нахилений вперед на 15–20°, лікті під 45°",
      },
      {
        name: "Жим гантелей на похилій лаві (верх грудей)",
        block: "Гантелі",
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        bodyPart: "upper",
        progressionStep: 2,
        restTimeInSeconds: REST_HEAVY,
        baselineWeightMin: 12,
        baselineWeightMax: 12,
        baselineNote: "2×12 кг",
        technique: "Лава під кутом 30°, акцент на верхню частину грудей",
      },
      {
        name: "Підтягування в Гравітоні широким хватом",
        block: "Гравітрон (Турнік)",
        targetSets: 3,
        targetRepsMin: 8,
        targetRepsMax: 10,
        bodyPart: "upper",
        progressionMode: "assist",
        progressionStep: 2,
        restTimeInSeconds: REST_HEAVY,
        baselineWeightMin: 23,
        baselineWeightMax: 23,
        baselineNote: "противага 23 кг",
        technique: "Долонями від себе, акцент на зведенні лопаток",
      },
      {
        name: "Горизонтальна тяга в блоці сидячи (вузький хват)",
        block: "Тренажери",
        targetSets: 3,
        targetRepsMin: 10,
        targetRepsMax: 12,
        bodyPart: "upper",
        progressionStep: 2,
        restTimeInSeconds: REST_MACHINE,
        baselineWeightMin: 39,
        baselineWeightMax: 39,
        baselineNote: "39 кг",
        technique: "Спина пряма, тягни лопатками, не корпусом",
      },
      {
        name: "Махи гантелей у нахилі (задня дельта)",
        block: "Гантелі",
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 15,
        bodyPart: "upper",
        progressionStep: 2,
        restTimeInSeconds: REST_ISOLATION,
        baselineWeightMin: 6,
        baselineWeightMax: 6,
        baselineNote: "2×6 кг",
      },
      {
        name: "Молоткові підйоми (Hammer Curls)",
        block: "Гантелі",
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 12,
        bodyPart: "upper",
        progressionStep: 2,
        restTimeInSeconds: REST_ISOLATION,
        baselineWeightMin: 10,
        baselineWeightMax: 10,
        baselineNote: "2×10 кг",
      },
      {
        name: "Канатні розгинання на трицепс у кросовері",
        block: "Тренажери",
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 15,
        bodyPart: "upper",
        progressionStep: 2,
        restTimeInSeconds: REST_ISOLATION,
        baselineWeightMin: 23,
        baselineWeightMax: 23,
        baselineNote: "23 кг",
      },
    ]),
  },
  {
    dayNumber: 4,
    weekday: "Неділя",
    name: "Низ B (акцент біцепс стегна та сідниці)",
    exercises: withWarmup([
      {
        name: "Румунська тяга з гантелями",
        block: "Гантелі",
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 12,
        bodyPart: "lower",
        progressionStep: 2,
        restTimeInSeconds: REST_HEAVY,
        baselineWeightMin: 14,
        baselineWeightMax: 14,
        baselineNote: "2×14 кг",
      },
      {
        name: "Розгинання ніг сидячи (Leg Extensions)",
        block: "Тренажери",
        targetSets: 4,
        targetRepsMin: 12,
        targetRepsMax: 15,
        bodyPart: "lower",
        progressionStep: 2,
        restTimeInSeconds: REST_MACHINE,
        baselineWeightMin: 73,
        baselineWeightMax: 73,
        baselineNote: "73 кг",
      },
      {
        name: "Підйоми на носки сидячи (Seated Calf Raises)",
        block: "Тренажери",
        targetSets: 4,
        targetRepsMin: 12,
        targetRepsMax: 20,
        bodyPart: "lower",
        progressionStep: 5,
        restTimeInSeconds: REST_ISOLATION,
        baselineWeightMin: 30,
        baselineWeightMax: 30,
        baselineNote: "30 кг",
        technique: "Акцент на камбаловидний м'яз, повільне опускання",
      },
      {
        name: "Розгинання рук з гантелями в нахилі (Kickbacks)",
        block: "Гантелі",
        targetSets: 3,
        targetRepsMin: 12,
        targetRepsMax: 12,
        bodyPart: "upper",
        progressionStep: 2,
        restTimeInSeconds: REST_ISOLATION,
        baselineWeightMin: 6,
        baselineWeightMax: 6,
        baselineNote: "2×6 кг",
      },
      {
        name: "Прогулянка фермера з гантелями",
        block: "Функціонал",
        targetSets: 3,
        targetRepsMin: 45,
        targetRepsMax: 45,
        bodyPart: "upper",
        exerciseType: "time",
        progressionStep: 2,
        restTimeInSeconds: REST_MACHINE,
        baselineWeightMin: 20,
        baselineWeightMax: 20,
        baselineNote: "2×20 кг",
        technique: "45 секунд на підхід, максимально стабільний темп",
      },
    ]),
  },
];
